version: '3'

services:
  db:
    image: mariadb
    restart: always
    env_file: .env
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1s
      timeout: 1s
      retries: 60

  filter:
    build:
      context: ./src/filter/
    restart: "no"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data.csv:/app/data/data.csv
    networks:
      - backend

  web:
    build:
      context: ./src/web
    env_file: .env
    restart: "always"
    depends_on:
      - filter
      - db
    networks:
      - backend
    ports:
      - "8000:8000"

networks:
  backend:
    driver: bridge
