version: '3'

services:
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MARIA_ROOT_PASSWORD: ${PSW}
    env_file: .env
    networks:
      - backend
    ports:
      - "3306:3306"

  filter:
    build:
      context: .
      dockerfile: ./src/filter/Dockerfile
    restart: no
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

  web:
    build:
      dockerfile: ./src/Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - db
      - filter
    networks:
      - backend
    ports:
      - "8088:8088"

networks:
  backend:
    driver: bridge

