version: '3'

services:
  db:
    image: mariadb
    restart: always
    env_file: .env
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1s
      timeout: 1s
      retries: 60

  filter:
    build:
      context: ./src/filter/
    restart: no
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    networks:
      - backend

#  web:
#    build:
#      dockerfile: ./src/Dockerfile
#    restart: on-failure
#    env_file: .env
#    depends_on:
#      - db
#      - filter
#    networks:
#      - backend
#    ports:
#      - "8088:8088"

networks:
  backend:
    driver: bridge
