version: '3'

services:
  db:
    image: mariadb
    container_name: db
    restart: "always"
    env_file: .env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1s
      timeout: 1s
      retries: 60
    networks:
      - backend
    ports:
      - "3306:3306"

  filler:
    container_name: filler
    build:
      context: ./src/filler
    restart: "no"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data.csv:/app/data/data.csv
    networks:
      - backend

  web:
    build:
      context: ./src/web
    container_name: web
    env_file: .env
    restart: "always"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8000:8000"

networks:
  backend:
    driver: bridge
